### ISSUE TITLE
[Submit add-on]: AIContentDescriber 2023.11.22.1

### ISSUE THREAD

**Issue by cartertemm** [nvaccess/addon-datastore#2044]
### Download URL

https://github.com/cartertemm/AI-content-describer/releases/download/v2023.11.22.1/AIContentDescriber-2023.11.22.1.nvda-addon

### Source URL

https://github.com/cartertemm/AI-content-describer

### Publisher

Carter Temm

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by lukaszgo1** [comment]
@cartertemm  Version number of your add-on is unfortunately not valid according to the store numbers - it can consists only of 3 groups of dot separated digits, so `2023.11.22.1` won't work.
While normally this would be reported by the validation code, it seems there is an error as follows:
``` Python
Traceback (most recent call last):
  File "D:\a\addon-datastore\addon-datastore\validation\_validate\createJson.py", line 87, in _createDictMatchingJsonSchema
    addonVersionNumber = MajorMinorPatch.getFromStr(manifest["version"])
  File "D:\a\addon-datastore\addon-datastore\validation\_validate\majorMinorPatch.py", line 19, in getFromStr
    raise ValueError(f"Version string not valid: {version}")
ValueError: Version string not valid: 2023.11.22.1
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
   File "D:\a\addon-datastore\addon-datastore\validation\_validate\createJson.py", line 222, in <module>
     main()
   File "D:\a\addon-datastore\addon-datastore\validation\_validate\createJson.py", line 207, in main
     generateJsonFile(
   File "D:\a\addon-datastore\addon-datastore\validation\_validate\createJson.py", line 45, in generateJsonFile
     data = _createDictMatchingJsonSchema(
   File "D:\a\addon-datastore\addon-datastore\validation\_validate\createJson.py", line 89, in _createDictMatchingJsonSchema
     manifest._errors = f"Manifest version invalid {addonVersionNumber}"
UnboundLocalError: local variable 'addonVersionNumber' referenced before assignment
```

**Comment by cartertemm** [comment]
@lukaszgo1 Appreciate the info! Yeah, date-based (yyyy.mm.dd) versioning seemed like a wonderful idea in theory, not so much in practice. I'm going to tackle an issue or two in the backlog to have something to show for the update then I'll open another here shortly.

**Comment by lukaszgo1** [comment]
Note that you can keep `yyyy.mm.dd`, as long as there is no fourth digit at the end, though this indeed excludes possibility to release two builds in the same day.
